name: "user-web"
port: 8021

user_srv:
    host: "127.0.0.1"
    port: 50051
    name: "user-srv"

jwt:
    key: "5$!UEmvB#nRB@Iwab#Sy!ZofKEOGLRtE"

sms:
    key: ""
    secrect: ""
    expire: 300

redis:
    host: "127.0.0.1"
    port: 6379

consul:
    host: "192.168.0.84"
    port: 8500